Add endpoint for anonymous comment via API
elpassion/el_debate pull request #33
Opened 2017-05-22 15:13 UTC by jestemkarol

2017-05-23 07:41 UTC, pawurb requested changes

2017-05-23 07:41 UTC, pawurb commented on app/controllers/api/comments_controller.rb
> +    @_debate ||= AuthToken.find_by_value(params.fetch(:auth_token)).debate
auth_token is sent in headers not params

2017-05-23 07:41 UTC, pawurb commented on app/models/comment.rb
> +class Comment < ApplicationRecord
this looks strange. you now have 2 models pointing to the same table. cannot you unify them somehow ? i think that only difference is that some comments have user and others not

2017-05-23 07:41 UTC, pawurb commented on app/serializers/comment_serializer.rb
> +    comment.user || anonymous_user
after unifying comment model you could move it there. then you won't need an empty user method anymore

2017-05-23 07:41 UTC, pawurb commented on spec/serializers/comment_serializer_spec.rb
> +  let(:slack_user) { create(:slack_user)}
missing space

2017-05-23 11:56 UTC, pawurb requested changes

2017-05-23 11:56 UTC, pawurb commented on app/controllers/api/comments_controller.rb
>    def debate
you already have a current_debate inherited from Api::ApplicationController

2017-05-23 11:56 UTC, pawurb commented on app/models/comment.rb
> +  belongs_to :slack_user, class_name: Slack::User, foreign_key: :slack_user_id
shouldn't it be an optional relation ? I think belongs_to checks presence by default

2017-05-23 11:56 UTC, pawurb commented on spec/services/comment_maker_spec.rb
> +    it "assigns a comment to a correct user if given" do
can you add a test checking that anonymous_user will be returned when slack user is missing ?

2017-05-23 14:04 UTC, pawurb requested changes

2017-05-23 14:04 UTC, pawurb commented on app/controllers/api/comments_controller.rb
> +    if debate
Did you test it ? debate variable does not exist at all. please add a comments_controller_spec

2017-05-23 14:04 UTC, pawurb commented on app/models/comment.rb
> +    OpenStruct.new(image_url: '/assets/dashboard/default_user.png', name: 'Anonymous')
you could cache it on a class level because it is constant. you can move it to class method and cache using class instance variable

2017-05-23 14:04 UTC, pawurb commented on app/serializers/comment_serializer.rb
> +      user_image_url: comment.user.image_url,
maybe you could delegate from model instead of chaining in serializer ? (law of demeter and stuff)

2017-05-23 14:26 UTC, jestemkarol commented on app/controllers/api/comments_controller.rb
> +    if debate
oversight, should be current_debate after last CR change

2017-05-24 08:21 UTC, pawurb commented on app/models/comment.rb
> +  delegate :image_url, :name, to: :user, prefix: true, allow_nil: true
you should not allow nil because if there is no slack_user there will be anonymous user

2017-05-24 08:21 UTC, pawurb commented on app/controllers/api/comments_controller.rb
> +    if current_debate
you use current_debate more then once. you should add caching because each time it executes a db query (in TokenRequester)

2017-05-24 08:56 UTC, merged