Replace avatars with user's initials on a colored background
elpassion/el_debate pull request #51
Opened 2017-07-25 11:54 UTC by cezarykaras

2017-07-25 15:00 UTC, grzegorzkemski requested changes

2017-07-25 15:00 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +    @avatarUrl       = comment.user_image_url
Wydaje mi się, że `image_url` nie powinien już być używany / mieć zastosowania. Czy można go usunąć?

2017-07-25 15:00 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +    @avatar_color    = comment.user_initials_avatar_color
Nazwa 'avatar' może być już teraz myląca, proponuję:
`@background_color = comment.user_initials_background_color`
`@user_initials = comment.user_initials`

2017-07-25 15:00 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +    @username        = comment.user_name
`user_name` też już chyba nie jest potrzebny?

2017-07-25 15:00 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +        $('<div>', { class: 'image'})
Pierdółka, brakuje spacji: `{ class: 'image' }`

2017-07-25 15:00 UTC, grzegorzkemski commented on app/assets/stylesheets/dashboard.scss
> +    .left .image .initials{
Spacja: `.initials {`

2017-07-25 15:00 UTC, grzegorzkemski commented on app/assets/stylesheets/dashboard.scss
> +    .left .image {
Nazwa klasy kontenera `.left` jest niesemantyczna. Co jak kiedyś po jakimś redesignie ten element wyląduje po prawej stronie? Nazwa powinna bardziej odzwierciedlać to co się znajduje wewnątrz kontenera, a nie gdzie on powinien być. 

Wiem, że to Ty nie dodałeś, ale zawsze dobrze pomalutku takie rzeczy poprawiać :)

2017-07-25 15:00 UTC, grzegorzkemski commented on app/assets/stylesheets/dashboard.scss
> +    .left .image {
Po drugie, nie ma tam już żadnego obrazka, więc nazwa `.image` też jest nieadekwatna. Sugeruję używać `.initials`.

2017-07-25 15:00 UTC, grzegorzkemski commented on app/models/comment.rb
> +  delegate :image_url, :name, :first_name, :last_name, :avatar_color, :initials,  to: :user, prefix: true
`image_url` i `name` do usunięcia (patrz wyżej)?

2017-07-25 15:00 UTC, grzegorzkemski commented on app/models/comment.rb
> +  delegate :image_url, :name, :first_name, :last_name, :avatar_color, :initials,  to: :user, prefix: true
`:avatar_color` => `:initials_background_color`

2017-07-25 15:00 UTC, grzegorzkemski commented on app/services/receive_allowed_colors.rb
> +class ReceiveAllowedColors
Myślę, że wydzielenie tej klasy raczej zaciemniło obraz jak to działa, zamiast rozjaśnić. Proponuję:

`class InitialsBackgroundColorGenerator `
..`POSSIBLE_COLORS = %w(#1abc9c ...)`
..` `
..`def self.call`
....`POSSIBLE_COLORS.sample`
..`end`
`end`

I oczywiście usunąć `ReceiveAllowedColors`. Co myślisz?

2017-07-25 15:00 UTC, grzegorzkemski commented on spec/services/initials_avatar_generator_spec.rb
> +    expect(ReceiveAllowedColors.call).to include(described_class.call)
Ten test to "zabetonowanie" implementacji. Powinniśmy testować zachowania:

`expect(described_class.new.call).to be_in(described_class::POSSIBLE_COLORS)`

2017-07-25 15:00 UTC, grzegorzkemski commented on spec/serializers/comment_serializer_spec.rb
> +  let(:mobile_user) { create(:edge_mobile_user, auth_token: auth_token, first_name: 'John', last_name: 'Doe') }
Wow, nie wiedziałem że mamy też "edge" modele. Moim zdaniem to overkill, jeżeli nie potrafimy ogarnąć różnicy pomiędzy API normalnym i edgowym w kontrolerach, to powinniśmy jeszcze raz przemyśleć to rozwiązanie.

2017-07-25 15:00 UTC, grzegorzkemski commented on spec/serializers/comment_serializer_spec.rb
> +    call = described_class.new(comment).to_h
Można użyć `subject`.

`subject { described_class.new(comment).to_h }`

`it '...' do`
..`expect(subject).to have_key(:xxx)`
..`expect(subject[:user_initials]).to eq('J D')`
`end`

2017-07-25 15:00 UTC, grzegorzkemski commented on spec/serializers/comment_serializer_spec.rb
> +  let(:mobile_user) { create(:edge_mobile_user, auth_token: auth_token, first_name: 'John', last_name: 'Doe') }
Na razie proponuję razem usiąść i się zastanowić jak się pozbyć tego modelu.

2017-07-25 15:00 UTC, grzegorzkemski commented on app/services/receive_allowed_colors.rb
> +     "#f2e7ba", "#efe0d2", "#e74c3c", "#f9ceca", "#b9cdce", "#efdec2", "#efdbce", "#ff8477", "#e1e9ef", "#d0eff2"]
Ogarnięte w komentarzu wyżej, ale zamiast `['a', 'b', 'c']` można użyć składni `%w(a b c)`. Zajmuje mniej miejsca i jest łatwiej dodawać i odejmować rzeczy :)

2017-07-25 15:00 UTC, grzegorzkemski commented on app/services/initials_avatar_generator.rb
> +class InitialsAvatarGenerator
To nie jest `InitialsAvatarGenerator` tylko `InitialsBackgroundColorGenerator`.

2017-07-25 15:00 UTC, grzegorzkemski commented on app/models/mobile_user.rb
> +    [self.first_name, self.last_name].compact.map { |s| s.first }.join(' ')
`self` jest tutaj niepotrzebny. Kwestia konwencji wiem, więc się nie upieram, ale moim zdaniem po co pisać coś co jest zbędne?

2017-07-25 15:00 UTC, grzegorzkemski commented on app/models/mobile_user.rb
> +    [self.first_name, self.last_name].compact.map { |s| s.first }.join(' ')
Zamiast `map { |s| s.first }` można pisać `map(&:first)` - jest mniej pisania, poza tym jest to szybsze (jakieś mikrosekundy, więc mało ważne, ale zawsze).

2017-07-25 15:12 UTC, cezarykaras commented on app/services/receive_allowed_colors.rb
> +class ReceiveAllowedColors
Ten serwis jest też wykorzystywany w testach, ale pomyślę jeszcze nad tym.

2017-07-25 15:12 UTC, cezarykaras commented on app/models/comment.rb
> +  delegate :image_url, :name, :first_name, :last_name, :avatar_color, :initials,  to: :user, prefix: true
image url i name będą usunięte w ramach tasku Maintenance: remove unnecessary "name" column from mobile user

2017-07-25 15:12 UTC, cezarykaras commented on app/assets/javascripts/dashboard/feed.js.coffee
> +    @avatarUrl       = comment.user_image_url
Było zachowane dla kompatybilności, ale w ramach tasku z ustawieniem edge jako głównej, wersji, image_url zostanie usunięte.

2017-07-25 15:12 UTC, cezarykaras commented on app/assets/javascripts/dashboard/feed.js.coffee
> +    @username        = comment.user_name
To będzie usunięte w ramach następnego tasku( api edge)

2017-07-25 15:14 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +    @avatarUrl       = comment.user_image_url
Przedyskutowane.

2017-07-25 15:15 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +    @username        = comment.user_name
Ok

2017-07-25 15:15 UTC, grzegorzkemski commented on app/models/comment.rb
> +  delegate :image_url, :name, :first_name, :last_name, :avatar_color, :initials,  to: :user, prefix: true
ok

2017-07-25 15:18 UTC, grzegorzkemski commented on app/services/receive_allowed_colors.rb
> +class ReceiveAllowedColors
Przedyskutowane

2017-07-26 07:51 UTC, cezarykaras commented on app/assets/stylesheets/dashboard.scss
> +    .left .image {
Nazwa klasy kontenera jest spowodowana wykorzystaniem frameworka sass-rails. Jest to klasa ustawiająca element po lewej stronie. Mogę zmienić nazwę i ustawić float na left w naszym pliku css, tylko czy jest sens to robić?

2017-07-26 09:07 UTC, cezarykaras commented on app/assets/stylesheets/dashboard.scss
> +    .left .image {
OK

2017-07-26 10:13 UTC, merged