Remove name column from mobile_user
elpassion/el_debate pull request #52
Opened 2017-07-26 11:50 UTC by cezarykaras

2017-07-26 15:51 UTC, grzegorzkemski requested changes

2017-07-26 15:51 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +      .append($('<strong>', { text: @first_name + ' ' + @last_name }))
[Opcjonalnie] W coffeescripcie możesz używać takiej samej konkatenacji stringów jak w rubym:

`"#{@first_name} #{@last_name}"`

2017-07-26 15:51 UTC, grzegorzkemski commented on app/controllers/api/comments_controller.rb
> +  before_action :update_first_and_last_name, unless: :first_and_last_name_present?
Trochę słabo, że taka logika jest w kontrolerze. Mamy takie opcje:
- przenieść to do `MobileUser`
- przenieść to do `CommentMaker`
- przenieść to do nowego serwisu, np. `MobileUserIdentityParams`

Pewnie ostatnia najlepsza, coś w tym stylu:
`if current_debate`
..`MobileUserIdentityParams.new(@mobile_user).update(first_name: params.dig(:first_name), last_name: params.dig(:last_name))`
..`...`
`end`

`class MobileUserIdentityParams`
..`...`
..`def update(first_name:, last_name:)`
....`mobile_user.update(first_name: first_name, last_name: last_name) unless has_identity?`
..`end`
..` `
..`private`
..` `
..`def has_identity?`
....`mobile_user.first_name.present? && mobile_user.last_name.present?`
..`end` 
`end`

Co myślisz? Może trochę overkill? Na pewno da to lepszy podział odpowiedzialności i łatwość testowania.

2017-07-26 15:51 UTC, grzegorzkemski commented on app/controllers/api/comments_controller.rb
> +  before_action :update_first_and_last_name, unless: :first_and_last_name_present?
Nie jestem też pewien co do nazwy. Alternatywnie `MobileUserCommentIdentity`, `MobileUserParams`, `CommenterIdentifier`, itp. Generalnie nazwa jest kluczowa, więc trzeba dobrze wybrać :)

2017-07-26 15:51 UTC, grzegorzkemski commented on app/controllers/api/comments_controller.rb
> +    @mobile_user.update_attributes(
Można też użyć `update` zamiast `update_attributes` (jest to zdaje się alias, a zawsze krócej).

2017-07-26 15:51 UTC, grzegorzkemski commented on app/assets/javascripts/dashboard/feed.js.coffee
> +      .append($('<strong>', { text: @first_name + ' ' + @last_name }))
Powinien być upcase inicjałów :)

2017-07-27 08:45 UTC, cezarykaras commented on app/controllers/api/comments_controller.rb
> +  before_action :update_first_and_last_name, unless: :first_and_last_name_present?
MobileUserIdentity

2017-07-27 20:56 UTC, grzegorzkemski requested changes

2017-07-27 20:56 UTC, grzegorzkemski commented on app/controllers/api/edge/comments_controller.rb
> +    MobileUserIdentity.new(@mobile_user, params).call
Znowu komentarz z serii nazewnictwo / czytelność kodu. Sorry, że tak się czepiam, ale to jest BARDZO ważne. BTW tu jest cytat, o którym Ci mówiłem: https://twitter.com/codinghorror/status/506010907021828096

Postuluję, żeby tutaj było:
`MobileUserIdentity.new(@mobile_user).update(first_name: params.dig(:first_name), last_name: params.dig(:last_name))`

Moje argumenty:
- Nazywanie metody `call` moim zdaniem jest bardzo mało informatywne. Co ta metoda robi? Odpowiedź "wywołuje się" jest dla mnie niewystarczająca :) Jeszcze gdyby serwis się nazywał `MobileUserIdentityUpdater`, to wtedy byłoby to lepsze, ale moim zdaniem i tak słaba praktyka - dobra jest taka, żeby nazwa metody dawała informację, co ona robi (w sensie zachowania). W tym wypadku aktualizuje tożsamość, czyli `MobileUserIdentity#update` :)
- Przekazywanie `params` przy tworzeniu serwisu jest niejasne - po co serwisowi `MobileUserIdentity` pełny zestaw parametrów z kontrolera? Co planujemy z nimi robić? Nie wiadomo. Natomiast wiadomo, że jak mamy `MobileUserIdentity` to przydałby się `mobile_user`, i moim zdaniem tylko to powinno być przekazywane do konstruktora. To, że są jakieś parametry, to jest brocha metody `update`.
- Metoda `update` powinna dostawać tylko te parametry, które są potrzebne, w tym wypadku `first_name` i `last_name`. Po co jej pozostałe? To tylko zaciemnia obraz.

2017-07-27 20:56 UTC, grzegorzkemski commented on app/controllers/api/edge/comments_controller.rb
> +    MobileUserIdentity.new(@mobile_user, params).call
Biorąc pod uwagę komentarz powyżej, wystarczy żeby było:

[w standardowym kontrolerze]
`def update_mobile_user_identity`
..`MobileUserIdentity.new(@mobile_user).update(first_name: params.dig(:first_name), last_name: params.dig(:last_name))`
`end`

[w kontrolerze edgeowym]
`def update_mobile_user_identity`
..`MobileUserIdentity.new(@mobile_user).update(first_name: params.fetch(:first_name), last_name: params.fetch(:last_name))`
`end`

I nie ma wtedy więcej różnic :)

2017-07-27 20:56 UTC, grzegorzkemski commented on spec/services/mobile_user_identity_spec.rb
> +    it 'chenge user identify' do
"changes", albo "updates"

2017-07-27 20:56 UTC, grzegorzkemski commented on spec/services/mobile_user_identity_spec.rb
> +    it 'chenge user identify' do
"changes", albo "updates"

2017-07-27 20:56 UTC, grzegorzkemski commented on spec/services/mobile_user_identity_spec.rb
> +  context 'When user has set first_name and last_name at initialize' do
Ponieważ stringi z `context`ów i `it`ów są łączone przez rspec w jeden ładny tekst, to dobrze zaczynać je z małej litery.

Przykład:
`describe MobileUserIdentity do`
..`context 'when something' do`
....`context 'and something' do`
......`it 'does something' do`
`...`

rspec złączy w logu jako `"MobileUserIdentity when something and something does something"` zamiast `"MobileUserIdentity When something And something Does something"` - wygląda dziwnie :)

2017-07-27 20:56 UTC, grzegorzkemski commented on app/models/mobile_user.rb
> +    "#{first_name} #{last_name}".titleize
Przydałoby się jeszcze zrobić `strip` (żeby ogarnąć użytkownika, który wpisał białe znaki):

`[first_name, last_name].compact.map(&:strip).join(' ').titleize`

...

2017-07-27 20:56 UTC, grzegorzkemski commented on app/models/mobile_user.rb
> +    [first_name, last_name].compact.map(&:first).join(' ').titleize
... i wtedy można tutaj dać:

`full_name.split.map(&:first).join`

Przy okazji usuwamy niepotrzebną spację między inicjałami, która tu była. A była tu bo brakuje testów do tej metody :) Trzeba dodać.

[Opcjonalnie] Praca domowa dla zaawansowanych: jak działa `full_name.scan(/\b\w/).join` i dlaczego nie możemy tutaj tego użyć? :)

2017-07-31 08:46 UTC, grzegorzkemski requested changes

2017-07-31 08:46 UTC, grzegorzkemski commented on spec/services/mobile_user_identity_spec.rb
> +    it 'chenges user identify' do
chAnges :)

2017-07-31 08:46 UTC, grzegorzkemski commented on spec/services/mobile_user_identity_spec.rb
> +    it 'chenges user identify' do
chAnges :)

2017-07-31 08:46 UTC, grzegorzkemski commented on spec/services/mobile_user_identity_spec.rb
> +      user.reload
Wydaje mi się, że w tym wypadku `user.reload` jest niepotrzebne (wszystkie operacje robione przez nasz serwis są robione bezpośrednio na naszej instancji).

2017-07-31 08:46 UTC, grzegorzkemski commented on spec/services/mobile_user_identity_spec.rb
> +      user.reload
Patrz wyżej.

2017-07-31 08:46 UTC, grzegorzkemski commented on app/models/mobile_user.rb
> +  def full_name
Brakuje testu do tej metody. Inicjały są testowane bardzo pośrednio, przez spec do `CommentSerializer`.

Przy okazji: warto by dodać case do nazwiska "First Last-LastName" => "FL".

2017-08-01 10:22 UTC, grzegorzkemski requested changes

2017-08-01 10:22 UTC, grzegorzkemski commented on spec/models/mobile_user_spec.rb
> +describe MobileUser, type: :model do
`type: :model` jest niepotrzebne

2017-08-01 10:22 UTC, grzegorzkemski commented on spec/models/mobile_user_spec.rb
> +      expect(mobile_user.full_name).to eq('John Last-lastname')
Moim zdaniem to powinno zwrócić `Last-Lastname` :(

2017-08-01 10:22 UTC, grzegorzkemski commented on spec/models/mobile_user_spec.rb
> +  context 'when last_name is short' do
Dodałbym jeszcze jeden kontekst, żeby było wiadomo co tak naprawdę testujemy.

`context 'identity params' do`
..`context 'when last name consists of only one part' do`
..`context 'when last name consists of two parts' do`

2017-08-02 11:17 UTC, grzegorzkemski requested changes

2017-08-02 11:17 UTC, grzegorzkemski commented on app/models/mobile_user.rb
> +    [first_name, last_name].compact.map{ |name| name.strip.capitalize }.join(' ').split('-').map(&:titleize).join('-')
`[first_name, last_name].compact.map { |name| name.strip.gsub(/^./, &:upcase) }.join(' ')`

2017-08-02 11:17 UTC, grzegorzkemski commented on spec/models/mobile_user_spec.rb
> +        expect(mobile_user.full_name).to eq('John Last-Lastname')
`expect(mobile_user.full_name).to eq('John Last-LastName')`

2017-08-02 14:39 UTC, merged